### ISSUE TITLE
404 https://wyam.io/modules/searchindex 

### ISSUE THREAD

**Issue by LokiMidgard** [Wyamio/Wyam.Web#35] opened 2017-02-12 11:12 UTC
I tried to look at the documentation of search index, but the wyam page gave me a 404.

I tried some other random  modules, they worked. But I didn't test all.

**Comment by daveaglick** [comment] 2017-02-16 22:42
Yikes! I think you *may* have found a bug in the Netlify web server :open_mouth:

**Comment by daveaglick** [comment] 2017-02-17 18:30
Netlify has confirmed this looks like a bug and are researching. I'll update or resolve the issue here once I get an update. Thanks for finding this.

**Comment by daveaglick** [comment] 2017-02-22 14:52
Resolved by Netlify

**Closed as completed by daveaglick** 2017-02-22 14:52 UTC
